
class WrapperError(Exception):...

class ConnectionError(WrapperError):...

class InsuficientBalance(WrapperError):...
class RepayExceedsBorrow(WrapperError):...

class BinanceKeyError(WrapperError): ...